const actions = {
    GET_SEARCH_BY_NAME: 'GET_SEARCH_BY_NAME',
    SET_SEARCH_BY_NAME: 'SET_SEARCH_BY_NAME',
    GET_SEARCH_BY_TAG: 'GET_SEARCH_BY_TAG',
    SET_SEARCH_BY_TAG: 'SET_SEARCH_BY_TAG'
}

export default actions
